### ISSUE TITLE
Allow drag and drop from another opened image of another tab of the browser

### ISSUE THREAD

**Issue by diodiogod** [nihedon/sd-webui-drop-anyware#1]
This is a great idea! Specially now that Forge new gradio thing was not allowing us to drop another image on top of an existing one in the png info tab (we needed to first click the X button to remove the image before dropping it).
But one thing your extension does not account for is dragging an image from another tab. I normally open a lot of generated images on other tabs, and then drag it to the info tab. Forge already allows it (if there is nothing on the png info tab). But it would be way easier to use you extension idea to be able to drop anywhere. 
Thanks!

**Comment by nihedon** [comment]
@diodiogod 
Thank you for the bug report as always!
I see, I hadn't considered dropping from another tab instead of from Explorer.
It definitely makes sense to support that as well.
I've implemented the fix, so please give it a try!

**Comment by diodiogod** [comment]
> @diodiogod Thank you for the bug report as always! I see, I hadn't considered dropping from another tab instead of from Explorer. It definitely makes sense to support that as well. I've implemented the fix, so please give it a try!

Brilliant! Works great. Thanks!
